# --- VDN specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
mac: "basic_mac_6h_vs_8z" # Basic controller
runner: "parallel"
batch_size_run: 8

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner_6h_vs_8z"
double_q: True
mixer: "vdn"

name: "vdn_smac_parallel"
